config/routes.rb
Rails.application.routes.draw do
  get 'recipelists/index'
  get 'recipes/index'
  get 'winelists/index'
  devise_for :users
  root "roots#index"
  resources :users, only: [:edit, :update] do
  end

  get '/about' => 'roots#about', as: 'about_root'
  get '/butler' => 'roots#butler', as: 'butler_root'
  get '/homepage' => 'roots#homepage', as: 'homepage_root'
  namespace :homepages do
    resources :winelists, only: [:index, :show]
    resources :recipelists, only: [:index, :show]
  end

  resources :wines do
    resources :cart_items, only: [:create]
  end
  
  resources :carts, only: [:create, :show] do
    resources :cart_items, only: [:destroy]
  end
  resources :wine_types
  resources :recipes
  resources :domaines, only: [:new, :create, :edit, :update]
  resources :sepages, only: [:new, :create]
  resources :roots, only: [:create] do
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :wines, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = Cart.find(params[:id])
  end

  def create
  end

  def pay
    binding.pry
    # Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp.api_key = 'sk_test_05a7ac4d534091ea7be7cbef'
    charge = Payjp::Charge.create(
      amount: 300,
      card: params['payjp-token'],
      currency: 'jpy'
    )
  end
end

app/views/carts/show.html.haml
= render "wines/shop_header"

.CartBody
  CARTS
  .Cart
    .Cart__Table
      %table.table.table-hover
        %thead
          %tr{:align => "center"}
            %td{:colspan => "2"} 商品
            %td{:width => "160"} 数量
            %td{:width => "130"} 小計
        %tbody
          - @cart.cart_items.each do |item|
            %tr{:height => "150"}
              %td{:align => "center"}
                = link_to wine_path(item.wine.id), class: 'no-underline' do
                  = image_tag item.wine.productimages[0].image_url, class: 'CratWine--image'
              %td{:width => "500"}
                .CratWine--element
                  = link_to wine_path(item.wine.id), class: 'no-underline' do
                    = item.wine.name
                .CratWine--element
                  = "生産者：#{item.wine.producer}"
                .CratWine--element
                  = "タイプ：#{item.wine.wine_type.group}"
                .CratWine--element
                  = "#{number_with_delimiter(item.wine.price)}円"
              %td{:align => "center"}
                %select{style: "height: 30px; width: 50px;"}
                  %option 1
                  %option 2
                  %option 3
                  %option 4
                  %option 5
                
                = link_to cart_cart_item_path(id: item.id, wine_id: item.wine_id, cart_id: @cart.id), method: :delete do
                  .btn{style: "margin-top: 20px; display: inline-block; height: 30px; width: 70px; background-color: rgb(136, 57, 57); color: #fff;"} 削除


              %td{:align => "center"}
                ????円
                                  
      %hr
    .Cart__Price
      合計　　　？？？円
      = form_tag(action: :pay, method: :post) do
        %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "購入する" ,"data-key" => "pk_test_126751eabfeb129cf8f136e0"}


    -# = form_tag action: :pay, method: :post do
    -#   -# = form_with url: carts_path do
    -#   :plain
    -#     <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="公開鍵"></script>