config/routes.rb
Rails.application.routes.draw do
  get 'recipelists/index'
  get 'recipes/index'
  get 'winelists/index'
  devise_for :users
  root "roots#index"
  resources :users, only: [:edit, :update] do
  end

  get '/about' => 'roots#about', as: 'about_root'
  get '/butler' => 'roots#butler', as: 'butler_root'
  get '/homepage' => 'roots#homepage', as: 'homepage_root'
  namespace :homepages do
    resources :winelists, only: [:index, :show]
    resources :recipelists, only: [:index, :show]
  end

  resources :wines do
    resources :cart_items, only: [:create]
  end
  
  resources :carts, only: [:create, :show] do
    resources :cart_items, only: [:destroy]
  end
  resources :wine_types
  resources :recipes
  resources :domaines, only: [:new, :create, :edit, :update]
  resources :sepages, only: [:new, :create]
  resources :roots, only: [:create] do
  end
end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :productimages
  belongs_to :domaine
  belongs_to :wine_type
  has_many :wine_sepages
  has_many :sepages, through: :wine_sepages
  has_many :cart_items
  has_many :carts, through: :cart_items

  accepts_nested_attributes_for :productimages, allow_destroy: true
  mount_uploader :score_image, ImageUploader

  def self.search(kind, current_user, top)
    case kind
    when "SP" then
      target_file = current_user.sparklingParame.score_image_url
      wines = Wine.where(wine_type_id: 1)
    when "B" then
      target_file = current_user.blancParame.score_image_url
      wines = Wine.where(wine_type_id: 2)
    when "R" then
      target_file = current_user.rougeParame.score_image_url
      wines = Wine.where(wine_type_id: 3)
    end

    data_array = []
    u_image = MiniMagick::Image.open("./public#{target_file}")
    u_numo_array = Numo::DFloat.cast(u_image.get_pixels)
    u_filename = current_user.blancParame.score_image_url

    
    wines.each do |wine|
      w_image = MiniMagick::Image.open("./public#{wine.score_image_url}")
      w_numo_array = Numo::DFloat.cast(w_image.get_pixels)
      w_filename = wine.score_image_url

      temp_data_params = { id: wine.id, file: w_filename, length: ((u_numo_array - w_numo_array).abs).sum }
      data_array << temp_data_params
    end
    results = data_array.sort_by { |b| b[:length] }[0..(top - 1)]
    wine_id = []
    results.each do |result|
      wine_id << result[:id]
    end
    Wine.where(id: [wine_id])
  end
end

app/models/wine_type.rb
class WineType < ApplicationRecord
  has_many :wines
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_search
  before_action :set_group

  def index
    @wines = @search.result.page(params[:page]).per(7)
  end

  def show
    @wine = Wine.find(params[:id])
    gon.taste = {body: @wine.body, fruit_flavor: @wine.fruit_flavor, taste: @wine.taste, acidity: @wine.acidity, astringency: @wine.astringency}
  end

  def new
    @wine = Wine.new
    @wine.productimages.build
  end

  def create
    @wine = Wine.new(wine_params)

    g = Gruff::Area.new 500
    g.title = "My Graph"
    g.theme_greyscale
    g.maximum_value = 10
    g.minimum_value = 0
    
    taste = []
    if @wine.attack != nil
      taste << @wine.attack
      key = taste.length - 1
      g.labels[key] = 'attack'
    end
    if @wine.body != nil
      taste << @wine.body
      key = taste.length - 1
      g.labels[key] = 'body'
    end
    if @wine.color != nil
      taste << @wine.color
      key = taste.length - 1
      g.labels[key] = 'color'
    end
    if @wine.flavor != nil
      taste << @wine.flavor
      key = taste.length - 1
      g.labels[key] = 'flavor'
    end
    if @wine.fruit_flavor != nil
      taste << @wine.fruit_flavor
      key = taste.length - 1
      g.labels[key] = 'fruit_flavor'
    end
    if @wine.sweetness != nil
      taste << @wine.sweetness
      key = taste.length - 1
      g.labels[key] = 'sweetness'
    end
    if @wine.bitterness != nil
      taste << @wine.bitterness
      key = taste.length - 1
      g.labels[key] = 'bitterness'
    end
    if @wine.acidity != nil
      taste << @wine.acidity
      key = taste.length - 1
      g.labels[key] = 'acidity'
    end
    if @wine.taste != nil
      taste << @wine.taste
      key = taste.length - 1
      g.labels[key] = 'taste'
    end
    if @wine.tannin != nil
      taste << @wine.tannin
      key = taste.length - 1
      g.labels[key] = 'tannin'
    end
    if @wine.astringency != nil
      taste << @wine.astringency
      key = taste.length - 1
      g.labels[key] = 'astringency'
    end

    g.data('data', taste)
    g.write("./app/assets/images/graph.png")

    image = File.open('./app/assets/images/graph.png')
    @wine.score_image = image
    if @wine.save
      redirect_to new_wine_path
    else
      render :index
    end
  end

  def edit
    @wine = Wine.find(params[:id])
  end

  def update
    @wine = Wine.find(params[:id])

    g = Gruff::Area.new 500
    g.title = "My Graph"
    g.theme_greyscale
    g.maximum_value = 10
    g.minimum_value = 0
    
    taste = []
    if @wine.attack != nil
      taste << @wine.attack
      key = taste.length - 1
      g.labels[key] = 'attack'
    end
    if @wine.body != nil
      taste << @wine.body
      key = taste.length - 1
      g.labels[key] = 'body'
    end
    if @wine.color != nil
      taste << @wine.color
      key = taste.length - 1
      g.labels[key] = 'color'
    end
    if @wine.flavor != nil
      taste << @wine.flavor
      key = taste.length - 1
      g.labels[key] = 'flavor'
    end
    if @wine.fruit_flavor != nil
      taste << @wine.fruit_flavor
      key = taste.length - 1
      g.labels[key] = 'fruit_flavor'
    end
    if @wine.sweetness != nil
      taste << @wine.sweetness
      key = taste.length - 1
      g.labels[key] = 'sweetness'
    end
    if @wine.bitterness != nil
      taste << @wine.bitterness
      key = taste.length - 1
      g.labels[key] = 'bitterness'
    end
    if @wine.acidity != nil
      taste << @wine.acidity
      key = taste.length - 1
      g.labels[key] = 'acidity'
    end
    if @wine.taste != nil
      taste << @wine.taste
      key = taste.length - 1
      g.labels[key] = 'taste'
    end
    if @wine.tannin != nil
      taste << @wine.tannin
      key = taste.length - 1
      g.labels[key] = 'tannin'
    end
    if @wine.astringency != nil
      taste << @wine.astringency
      key = taste.length - 1
      g.labels[key] = 'astringency'
    end

    g.data('data', taste)
    g.write("./app/assets/images/graph.png")

    image = File.open('./app/assets/images/graph.png')
    @wine.score_image = image

    if @wine.update(wine_params)
      redirect_to edit_wine_path(@wine.id + 1)
    else
      render :index
    end
  end

  def destroy
  end

  private
  def wine_params
    params.require(:wine).permit( :name,
                                  :name_spell,
                                  :title,
                                  :comment,
                                  :producer,
                                  :wine_type_id,
                                  :domaine_id,
                                  :chator,
                                  :price,
                                  :attack,
                                  :body,
                                  :color,
                                  :flavor,
                                  :fruit_flavor,
                                  :sweetness,
                                  :bitterness,
                                  :acidity,
                                  :taste,
                                  :tannin,
                                  :astringency,
                                  :score_image,
                                  :score,
                                  :taste_comment,
                                  :aoc,
                                  :cuisine,
                                  sepage_ids: [],
                                  productimages_attributes:[
                                      :id,
                                      :wine_id,
                                      :image,
                                      :_destroy
                                      ])
  end

  def set_group
    @cart = Cart.find(current_user.cart.id)
  end

  def set_search
    @search = Wine.ransack(params[:q])
  end
end

app/views/wines/_productimage_fields.html.haml
.nested-fields
  .CreateForm__leftField
    = f.label :image, "画像", class: 'CreateForm__label'
  .CreateForm__rightField
    = f.file_field :image, class: 'CreateForm__input'
    = link_to_remove_association '削除', f

app/views/wines/_shop_header.html.haml
.PaddingBox
.WineHeader
  .SearchField
    .SearchField__online
      online shop
    .SearchField__left
      -# = search_form_for @search, class: '' do |f|
      -#   %input_tag{type: 'submit', class: "SearchField__left--icon"}
      -#     = icon('fas', 'search search-icon', class: "")
      -#   = f.search_field :name_cont, class: 'SearchField__left--inpput', placeholder: 'Search Field'
        
    .SearchField__right
      %ul.IconBox
        = link_to "#", class: "IconBox__Btn" do
          %li
            .IconBox__count
            = icon('fas', 'file-invoice-dollar', class: "IconBox--icon")
            購入履歴
        = link_to "#", class: "IconBox__Btn" do
          %li
            .IconBox__count
            = icon('fas', 'history', class: "IconBox--icon")
            閲覧履歴
        = link_to "#", class: "IconBox__Btn" do
          %li
            .IconBox__count
              -# - if !@cart.cart_items.size.blank?
              -#   .IconBox__count--num
              -#     = @cart.cart_items.size
            = icon('far', 'heart', class: "IconBox--icon")
            お気に入り
        = link_to cart_path(current_user.cart.id), class: "IconBox__Btn" do
          %li
            .IconBox__count
              - if !@cart.cart_items.size.blank?
                .IconBox__count--num
                  = @cart.cart_items.size
            = icon('fas', 'cart-arrow-down', class: "IconBox--icon")
            カート
  %hr
 
.PaddingBox2

app/views/wines/edit.html.haml
.Content
  %h1 新規ワイン登録フォーム
  .CreateForm
    = form_with model: @wine , local: true do |f|
      %table.CreateForm__Info
        %tbody
          %tr
            %th
              = f.label :name, "ワイン名", class: 'CreateForm__label'
            %td
              = f.text_field :name, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :name_spell, "スペル表記", class: 'CreateForm__label'
            %td
              = f.text_field :name_spell, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :title, "サブコメント", class: 'CreateForm__label'
            %td
              = f.text_field :title, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :comment, "詳細", class: 'CreateForm__label'
            %td
              = f.text_area :comment, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :taste_comment, "味わい", class: 'CreateForm__label'
            %td
              = f.text_area :taste_comment, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :producer, "生産者", class: 'CreateForm__label'
            %td
              = f.text_field :producer, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :domaine_id, "生産国", class: 'CreateForm__label'
            %td
              = f.collection_select :domaine_id, Domaine.all, :id, :name, include_blank: "選択して下さい"
          %tr
            %th
              = f.label :chator, "ドメーヌ", class: 'CreateForm__label'
            %td
              = f.text_field :chator, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :price, "価格", class: 'CreateForm__label'
            %td
              = f.text_field :price, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :aoc, "AOC", class: 'CreateForm__label'
            %td
              = f.text_field :aoc, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :cuisine, "お勧め料理", class: 'CreateForm__label'
            %td
              = f.text_field :cuisine, class: 'CreateForm__input', placeholder: ''
      .CreateForm__field
        = f.fields_for :productimages do |op|
          = render 'productimage_fields', f: op
          .links
            = link_to_add_association '＋別の商品を追加', f, :productimages
        -# = f.fields_for :productimages do |image_form|
        -#   .CreateForm__leftField
        -#     = image_form.label :image, "画像", class: 'CreateForm__label'
        -#   .CreateForm__rightField
        -#     = image_form.file_field :image, class: 'CreateForm__input'

      .CreateForm__field
        .CreateForm__leftField
          = f.label :wine_type_id, "タイプ", class: 'CreateForm__label'
        .CreateForm__rightField
          = f.collection_select :wine_type_id, WineType.all, :id, :group, include_blank: "選択して下さい"
      .CreateForm__field
        .CreateForm__leftField
          = f.label :sepage_name, "品種", class: 'CreateForm__label'
        .CreateForm__rightField
          = f.collection_check_boxes :sepage_ids, Sepage.all, :id, :name

      %table.CreateForm__taste
        %tbody
          %tr
            %th
              = f.label :attack, "アタック", class: 'CreateForm__label'
            %td
              = f.number_field :attack, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :body, "ボディ", class: 'CreateForm__label'
            %td
              = f.number_field :body, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :color, "色調", class: 'CreateForm__label'
            %td
              = f.number_field :color, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :flavor, "フレーバー", class: 'CreateForm__label'
            %td
              = f.number_field :flavor, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :fruit_flavor, "果実味", class: 'CreateForm__label'
            %td
              = f.number_field :fruit_flavor, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :sweetness, "甘味", class: 'CreateForm__label'
            %td
              = f.number_field :sweetness, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :bitterness, "苦味", class: 'CreateForm__label'
            %td
              = f.number_field :bitterness, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :acidity, "酸味", class: 'CreateForm__label'
            %td
              = f.number_field :acidity, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :taste, "コク", class: 'CreateForm__label'
            %td
              = f.number_field :taste, class: 'CreateForm__input', placeholder: ''
          %tr
            -# %th
            -#   = f.label :tannin, "タンニン", class: 'CreateForm__label'
            -# %td
            -#   = f.number_field :tannin, class: 'CreateForm__input', placeholder: ''
            -# %th
            -#   = f.label :astringency, "渋み", class: 'CreateForm__label'
            -# %td
            -#   = f.number_field :astringency, class: 'CreateForm__input', placeholder: ''
      .CreateForm__field
        .CreateForm__leftField
        .CreateForm__rightField
          = f.submit '登録', class: 'Form__submitBtn'

app/views/wines/index.html.haml
= render "shop_header"

.WineBody
  .WineSide
    .WineSide--search
      タイプ
    .WineSide--element
      - WineType.all.each do |type|
        = link_to type.group, wines_path({q: {"wine_type_id_eq": type.id, commit: "Search" }})
        %br
    %hr
    .WineSide--search
      産地
    .WineSide--element
      - Domaine.all.each do |domaine|
        = link_to domaine.name, wines_path({q: {"domaine_id_eq": domaine.id, commit: "Search" }})
        %br
    %hr
    -# .WineSide--search
    -#   品種
    -# .WineSide--element
    -#   - Sepage.all.each do |sepage|
    -#     = link_to sepage.name, wines_path({q: {"wine.wine_sepages_id_eq": sepage.id, commit: "Search" }})
    -#     %br
    -# %hr
    .WineSide--search
      価格
    .WineSide--element
      
    %hr

  .WineMainField
    .Sort_field
      .Sort_field__box
        Search Sort：
        = link_to "", class: "" do
          = sort_link(@search, :name, "商品名")
        = link_to "", class: "" do
          = sort_link(@search, :price, "価格")
        = link_to "", class: "" do
          = sort_link(@search, :domaine_id, "生産地")
        = link_to "", class: "" do
          = sort_link(@search, :wine_type_id, "タイプ")
    .Products
      - @wines.each do |wine|
        .Products__Box
          .Products__Box__left
            = link_to wine_path(wine.id), class: 'no-underline' do
              = image_tag wine.productimages[0].image_url, class: 'Products__Box__left--image'
          .Products__Box__center
            .Products__Box__center--name
              = link_to wine_path(wine.id), class: 'no-underline' do
                = wine.name
            .Products__Box__center--info
              = wine.name_spell
            .Products__Box__center--info
              = "生産者：#{wine.producer}"
            .Products__Box__center--info
              = "タイプ：#{wine.wine_type.group}"
            .Products__Box__center--info
              生産地：
              = image_tag wine.domaine.flag_url, class: 'frag_image'
              = "#{wine.domaine.name} / #{wine.chator}"
            .Products__Box__center--info
              = "説　明：#{wine.title}"
          %hr 
          .Products__Box__right
            = "#{number_with_delimiter(wine.price)}円"
        %hr
      .p-top__paginate
        = paginate @wines

app/views/wines/new.html.haml
.Content
  %h1 新規ワイン登録フォーム
  .CreateForm
    = form_with model: @wine , local: true do |f|
      %table.CreateForm__Info
        %tbody
          %tr
            %th
              = f.label :name, "ワイン名", class: 'CreateForm__label'
            %td
              = f.text_field :name, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :name_spell, "スペル表記", class: 'CreateForm__label'
            %td
              = f.text_field :name_spell, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :title, "サブコメント", class: 'CreateForm__label'
            %td
              = f.text_field :title, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :comment, "詳細", class: 'CreateForm__label'
            %td
              = f.text_area :comment, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :taste_comment, "味わい", class: 'CreateForm__label'
            %td
              = f.text_area :taste_comment, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :producer, "生産者", class: 'CreateForm__label'
            %td
              = f.text_field :producer, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :domaine_id, "生産国", class: 'CreateForm__label'
            %td
              = f.collection_select :domaine_id, Domaine.all, :id, :name, include_blank: "選択して下さい"
          %tr
            %th
              = f.label :chator, "ドメーヌ", class: 'CreateForm__label'
            %td
              = f.text_field :chator, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :price, "価格", class: 'CreateForm__label'
            %td
              = f.text_field :price, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :aoc, "AOC", class: 'CreateForm__label'
            %td
              = f.text_field :aoc, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :cuisine, "お勧め料理", class: 'CreateForm__label'
            %td
              = f.text_field :cuisine, class: 'CreateForm__input', placeholder: ''
      .CreateForm__field
        = f.fields_for :productimages do |op|
          = render 'productimage_fields', f: op
          .links
            = link_to_add_association '＋別の商品を追加', f, :productimages
        -# = f.fields_for :productimages do |image_form|
        -#   .CreateForm__leftField
        -#     = image_form.label :image, "画像", class: 'CreateForm__label'
        -#   .CreateForm__rightField
        -#     = image_form.file_field :image, class: 'CreateForm__input'

      .CreateForm__field
        .CreateForm__leftField
          = f.label :wine_type_id, "タイプ", class: 'CreateForm__label'
        .CreateForm__rightField
          = f.collection_select :wine_type_id, WineType.all, :id, :group, include_blank: "選択して下さい"
      .CreateForm__field
        .CreateForm__leftField
          = f.label :sepage_name, "品種", class: 'CreateForm__label'
        .CreateForm__rightField
          = f.collection_check_boxes :sepage_ids, Sepage.all, :id, :name

      %table.CreateForm__taste
        %tbody
          %tr
            %th
              = f.label :attack, "アタック", class: 'CreateForm__label'
            %td
              = f.number_field :attack, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :body, "ボディ", class: 'CreateForm__label'
            %td
              = f.number_field :body, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :color, "色調", class: 'CreateForm__label'
            %td
              = f.number_field :color, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :flavor, "フレーバー", class: 'CreateForm__label'
            %td
              = f.number_field :flavor, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :fruit_flavor, "果実味", class: 'CreateForm__label'
            %td
              = f.number_field :fruit_flavor, class: 'CreateForm__input', placeholder: ''
            -# %th
            -#   = f.label :sweetness, "甘味", class: 'CreateForm__label'
            -# %td
            -#   = f.number_field :sweetness, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :bitterness, "苦味", class: 'CreateForm__label'
            %td
              = f.number_field :bitterness, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :acidity, "酸味", class: 'CreateForm__label'
            %td
              = f.number_field :acidity, class: 'CreateForm__input', placeholder: ''
            -# %th
            -#   = f.label :taste, "コク", class: 'CreateForm__label'
            -# %td
            -#   = f.number_field :taste, class: 'CreateForm__input', placeholder: ''
          %tr
            %th
              = f.label :tannin, "タンニン", class: 'CreateForm__label'
            %td
              = f.number_field :tannin, class: 'CreateForm__input', placeholder: ''
            %th
              = f.label :astringency, "渋み", class: 'CreateForm__label'
            %td
              = f.number_field :astringency, class: 'CreateForm__input', placeholder: ''
      .CreateForm__field
        .CreateForm__leftField
        .CreateForm__rightField
          = f.submit '登録', class: 'Form__submitBtn'

app/views/wines/show.html.haml
= javascript_include_tag 'wines'
= render "shop_header"

.WineItemInfomation
  .Product
    .Product__Left
      .Product__Left__ImageBox
        %ul#list
          %li
            = image_tag @wine.productimages[1].image_url, class: 'List--image'
          %li
            = image_tag @wine.productimages[0].image_url, class: 'List--image'
        #main
          = image_tag @wine.productimages[1].image_url, class: 'Main--image'
      -# .Product__Left--flever
      -#   フレーバー
      .Product__Left--body
        %h4 ボディ
        .Bar__Para
          .Bar__Para__bar
            .Bar__Para__bar--ele
              = @wine.body
          .Bar__Para--body
            ライトボディ　　　　ミディアムボディ　　　　フルボディ
      .Product__Left--taste
        %h4 味わい
        %canvas#myChart
    .Product__Right
      .WineInfo
        .WineInfo__top
          - case @wine.wine_type_id
            - when 1 then
              .WineInfo__top--nameSpell.sparkling
                = @wine.name_spell
              .WineInfo__top--name.sparkling
                = @wine.name
            - when 2 then
              .WineInfo__top--nameSpell.blanc
                = @wine.name_spell
              .WineInfo__top--name.blanc
                = @wine.name
            - when 3 then
              .WineInfo__top--nameSpell.rouge
                = @wine.name_spell
              .WineInfo__top--name.rouge
                = @wine.name
          .WineInfo__top--title
            = @wine.title
        .WineInfo__Price
          .WineInfo__Price__price
            = "#{number_with_delimiter(@wine.price)}円"
          .WineInfo__Price__cart
            = link_to wine_cart_items_path(@wine.id), method: :post do
              %button.btn{style: "display: inline-block; height: 50px; width: 150px; background-color: #440000; color: gold;"} カートに入れる
        %hr

        .WineInfo__SubInfo
          = @wine.comment
        %hr
        .WineInfo__TasteComment
          - case @wine.wine_type_id
            - when 1 then
              .WineInfo__TasteComment--ele.WineInfo__TasteComment--SP 味わい
            - when 2 then
              .WineInfo__TasteComment--ele.WineInfo__TasteComment--B 味わい
            - when 3 then
              .WineInfo__TasteComment--ele.WineInfo__TasteComment--R 味わい
          = @wine.taste_comment
        %hr
        .WineInfo__ParsonalData
          %table.Product__table
            %tbody
              %tr
                %th 生産者
                %td
                  = @wine.producer
              %tr
                %th 生産地
                %td
                  = image_tag @wine.domaine.flag_url, class: 'frag_image'
                  = "#{@wine.domaine.name} / #{@wine.chator}"
              %tr
                %th 原産地呼称
                %td
                  = @wine.aoc
              %tr
                %th タイプ
                %td
                  = @wine.wine_type.group
              %tr
                %th 品種
                %td
                  - @wine.sepages.each do |sepage|
                    = sepage.name
                    %br
              %tr
                %th おすすめ料理
                %td
                  = @wine.cuisine