config/routes.rb
Rails.application.routes.draw do
  get 'recipelists/index'
  get 'recipes/index'
  get 'winelists/index'
  devise_for :users
  root "roots#index"
  resources :users, only: [:edit, :update] do
  end

  get '/about' => 'roots#about', as: 'about_root'
  get '/butler' => 'roots#butler', as: 'butler_root'
  get '/homepage' => 'roots#homepage', as: 'homepage_root'
  namespace :homepages do
    resources :winelists, only: [:index, :show]
    resources :recipelists, only: [:index, :show]
  end

  resources :wines do
    resources :cart_items, only: [:create]
  end
  
  resources :carts, only: [:create, :show] do
    resources :cart_items, only: [:destroy]
  end
  resources :wine_types
  resources :recipes
  resources :domaines, only: [:new, :create, :edit, :update]
  resources :sepages, only: [:new, :create]
  resources :roots, only: [:create] do
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Majordone
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    %script{src: "https://unpkg.com/scrollreveal"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"}
    = include_gon
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .HeaderList
        = link_to root_path, class: 'HeaderList__Logo' do
          = image_tag ('majordone_logo.svg'), class: 'top_logo'
        - if user_signed_in?
          .menu
            %div MENU
            %div.menu-trigger{ href: '#'}
              %span
              %span
              %span
        - else
          .menu
            = link_to about_root_path, class: "about--btn"  do
              MaJordomeについて
    - if user_signed_in?
      %nav#slide-menu
        .user-info
          .user-info__image
            = image_tag ('somliere.svg'), class: 'somliere'
          .user-info__name
            UserName :
            %h4
              = current_user.nickname
        .MENU_LIST
          .MENU_LIST--top
            MAIN MENU
          %ul
            = link_to butler_root_path, class: 'no-underline' do
              %li Butler
            = link_to wines_path, class: 'no-underline' do
              %li online Shop
            = link_to recipes_path, class: 'no-underline' do
              %li Recipes
        .MENU_LIST
          .MENU_LIST--top
            USER MENU
          %ul
            = link_to homepage_root_path, class: 'no-underline' do
              %li My Menu
            = link_to homepages_winelists_path, class: 'no-underline' do
              %li My Wine List
            = link_to homepages_recipelists_path, class: 'no-underline' do
              %li My Recipe
            = link_to edit_user_path(current_user.id), class: 'no-underline' do
              %li user_edit
            = link_to destroy_user_session_path, method: :delete, class: 'no-underline' do
              %li logout


          
    = yield

    %footer
      &copy; 2020 T-Nakamura